### ISSUE TITLE
Marge should not merge MRs with failed CI unless explicity stated by a config.

### ISSUE THREAD

**Issue by alatiera** [smarkets/marge-bot#100]
So here is the scenario, we setup marge with default config and made a failing MR to test. We assigned marge to the MR but instead of complaining it did go ahead and merge it since we hadn't yet turned on this giltlab [flag][1] for the project. 

I think Marge should prevent stupid mistakes like this and have it require a flag be set if you **really** want her to merge failing CI MR.

[1]: https://gitlab.com/help/user/project/merge_requests/merge_when_pipeline_succeeds#only-allow-merge-requests-to-be-merged-if-the-pipeline-succeeds

**Comment by grebois** [comment]
Had the same problem

**Comment by JaimeLennox** [comment]
Makes sense to me. Would you be interested in submitting a patch?

**Comment by John-Colvin** [comment]
So what is actual behaviour supposed to be currently.

In the README it says `If anything goes wrong (merge conflicts, tests that fail, etc.) she'll leave a message on the merge-request, so you'll get notified.`

So if a MR is rebased by marge and tests fail, it wont be merged, but if it's already failing & does not need rebasing then marge will happily merge it? Is there a difference between when the tests failed i.e. already failed when marge was assigned or failed after assignment? Along the same lines, does the time the build is triggered affect this?

**Comment by aschmolck** [comment]
Basically the feature under discussion is adding an extra safety check in case you misconfigured your gitlab project. I.e. if you want to only merge green builds but didn't tick `Only allow merge requests to be merged if the pipeline succeeds`. If you don't check this tickbox, marge will ignore the CI status, just as gitlab will in that case (when pressing the merge/rebase button in the UI).

When CI fails and what marge rewrote or not has absolutely no influence on this: if you tell gitlab you don't care about CI failures, neither will marge, in all cases. And if you do tell gitlab you don't want to be able to merge  w/o green builds, marge will always respect the build flag.

So this flag only makes sense if you assume people who use marge probably want CI failure to block bad merges, even if they didn't set up their gitlab project that way.

But no one has submitted a MR for this, and it seems to confuse people so I'm just gonna close this.
