### ISSUE TITLE
Syntax error for using bare asterisk as function args

### ISSUE THREAD

**Issue by guoqiao** [smarkets/marge-bot#106]
As I known, in Python, you can use this syntax to force caller of function to use keyword args after *:

```
def func(a, b, *, c=None, d=None):
    ....
```
Which means, caller have to call func with:
```
result = func(a, b, c="c-value", d="d-value")
```
Other than:
```
result = func(a, b, "c-value", "d-value")
```

However, in marge-bot source code, I found such examples:
```
class Bot(object):                                                              
    def __init__(self, *, api, config):                                          
        self._api = api                                                         
        self._config = config
        ....
...

class MergeJob(object):

    def __init__(self, *, api, user, project, merge_request, repo, options):
        self._api = api
        self._user = user
        self._project = project
        ....
```

And I got SyntaxError for those lines in both Python2 and Python3.  

Just wondering what am doing wrong, and why didn't other people encount this error?

**Comment by aschmolck** [comment]
You're using an old version of python, this doesn't work with python 2. I believe, but am too lazy to look it up now, that the `*` syntax was there from early python3.

Works for me:

```> ipython
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)                         
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: class MergeJob(object):
   ...: 
   ...:     def __init__(self, *, api, user, project, merge_request, repo, options):
   ...:         self._api = api
   ...:         self._user = user
   ...:         self._project = project
In [2]: MergeJob
Out[2]: <class '__main__.MergeJob'>
```

Also note that marge-bot is developed on python 3.6 and no particular effort has been taken to make it compatible to older versions of python (since people who have an old python install can fairly easily use the docker image we provide or a nix-build instead). I don't think this is explicitly mentioned anywhere, so we should do that.

**Comment by guoqiao** [comment]
I was testing Python 2.7.12 and 3.5.3, neither worked. Later I figure out from code that marge-bot can only run with Python 3.6.
The * syntax was in Python 3 for a long while, that's true. But only when you use it as in my example: args after * should all be keyword args. The usage in Marge-Bot code is unusual and only work with 3.6.

I do recommend we mention this in README, since Python 3.6 is not available for most Linux dists at the moment, which will cause confusion for most new users.
