### ISSUE TITLE
Question: what is a "normal" workflow to resolve rebasing conflict?

### ISSUE THREAD

**Issue by AntonPetrov83** [smarkets/marge-bot#133]
Hi!

How am I expected to resolve rebasing conflicts?
When I rebase feature branch onto master localy my rebased `feature-branch` tip is detached from the `origin/feature-branch` and I cannot just push. So, it looks like I have to manually delete `origin/feature-branch` then push my "new" rebased `feature-branch` and create new MR.

Is it okay?

How do you resolve this?

**Comment by JaimeLennox** [comment]
You can force push to your branch, i.e. `git push -f origin feature-branch:feature-branch`.

**Comment by AntonPetrov83** [comment]
Force pushing will require to create new MR, right? Because this is how GitLab works. So I will loose history of discussions related to the original MR?

**Comment by JaimeLennox** [comment]
No, it does not. All the discussion is kept; this is akin to appending commits to your existing MR, or squashing them; GitLab knows how to handle this.

**Comment by AntonPetrov83** [comment]
You are right.  Thank you, @JaimeLennox

**Comment by JaimeLennox** [comment]
No worries!
