### ISSUE TITLE
Feature request: Docker image of Master 

### ISSUE THREAD

**Issue by grebois** [smarkets/marge-bot#139]
Latest tag is 3 months old, https://hub.docker.com/r/smarkets/marge-bot/tags/

There has been a lot of progress since 0.7.0, would be nice to have a tag master.

Best!

**Comment by JaimeLennox** [comment]
I can look into adding this - it seems reasonable given we've taken a while to release a new version. Having said that, we'll probably release a new version quite soon!

**Comment by grebois** [comment]
Awesome, thanks @JaimeLennox
