### ISSUE TITLE
Handle autosquash

### ISSUE THREAD

**Issue by aschmolck** [smarkets/marge-bot#14]
Ticking autosquash seems to break marge at moment.

**Comment by jcpetruzza** [comment]
I've investigated the problematic merge-request that lead to this issue being opened and it turns out auto-squash was a red-herring: the actual problem was actually another instance of #32.

It was good anyway that it made us notice we needed something like #45 to be implemented.

**Comment by aschmolck** [comment]
@jcpetruzza yeah, I know should have updated the bug description. It's still  kinda true though, it interacts badly with any of the `--add*` flags.
