### ISSUE TITLE
feature: add rebase-then-merge strategy

### ISSUE THREAD

**Issue by elaforge** [smarkets/marge-bot#140]
I think I need a strategy that tries rebase, if that fails, tries merge from head, and only give up when both fail.

I'll start a fork and send a PR, but I thought I should mention it here first in case there's already a better way to do it, or it's definitely a bad idea for some reason I didn't think of.

**Comment by jcpetruzza** [comment]
Out of curiosity, what's the use-case for this? For instance, if a rebase fails it will because of conflict and it that case I'd expect the merge to fail as well?

**Comment by elaforge** [comment]
Not necessarily!  I just tested this out to make sure I'm not just making things up.  Say someone has a branch and adds a change.  Head accumulates a new conflicting one, and they merge head to their branch and resolve the conflict.  Now if head accumulates an additional non-conflicting change, a rebase against head will fail, but a merge from head will not.

However this is not a ff-merge so git will want to open an editor.  I don't see in the source how marge handles that, so maybe `Repo.merge` is intended only for ff-merges?  In any case I assume I would have to pass a `-m`.

The background is that people generally do rebases but sometimes have a large branch that they share with others before merging, at which point they prefer to merge from head.  We'd like to have marge rebase when possible to keep the history simpler, but also allow the merge-from-head folks to use the marge-queue, as long as there are no true conflicts.

**Comment by JaimeLennox** [comment]
If I understand the situation correctly, why not just rebase the branch on HEAD instead of merging the changes? This way you can still resolve the conflicts and you won't get issues with non-conflicting changes.

**Comment by elaforge** [comment]
The rebase will fail, asking to re-resolve the conflict that you already resolved in the previous merge from head.  Here's a more detailed reproduction:

- git init
- add file `a` master, with a single line
- `git branch branch`
- modify `a`, commit to master
- checkout `branch`, and modify the line in `a` in some other way
- now `branch` conflicts with `master`, so `git merge master` and resolve it
- `git checkout master`, now add a non-conflicting change, like a new file `b`
- `git checkout branch`

Now if you try `git rebase master` it will ask for manual resolution, even though `master` has only added a non-conflicting file.  `git merge master -m msg` will work without intervention though.

If the question is why not ask people to stop doing merges from head, see the previous comment...

**Comment by JaimeLennox** [comment]
Ah my bad, I misread that part - but yes, your last point was what I was referring to. I see the use case now.

**Comment by elaforge** [comment]
Closing, due to lack of interest.
