### ISSUE TITLE
Testsuite assumes python3 is installed

### ISSUE THREAD

**Issue by mpickering** [smarkets/marge-bot#162]
@jcpetruzza suggested I ran the tests with

```
nix-shell --run py.test
```

Which works really well apart from the fact that some tests assume that `python3` is installed on your path. It would be good to add a specific `shell.nix` which enables a clean run of the testsuite.

**Comment by aschmolck** [comment]
What error do you get if you run `nix-shell --pure --run py.test` ?

**Comment by aschmolck** [comment]
Closing this due to lack of follow-up.
