### ISSUE TITLE
marge-bot reporting "GitLab provided no user permissions"

### ISSUE THREAD

**Issue by snim2** [smarkets/marge-bot#165]
I have an instance of `marge-bot` running in Docker against a set of repos on https://gitlab.com.

`marge-bot` is running as a user which is the owner of all the repos in the group and with a Personal Access Token that has `api` permissions.

Even so, I'm getting:

```sh
2019-03-07 16:22:51,526 INFO Sleeping for 30 seconds...
2019-03-07 16:23:21,532 INFO Finding out my current projects...
2019-03-07 16:23:23,287 WARNING Ignoring project PROJECT since GitLab provided no user permissions
...
```

for all projects that match the regexp. 

This is how I'm running the bot:

```sh
docker run --restart=on-failure \
  -e MARGE_AUTH_TOKEN="$(cat FILE.token)" \
  -e MARGE_SSH_KEY="$(cat FILE)" \
  smarkets/marge-bot \
  --gitlab-url='https://gitlab.com' \
  --embargo='Friday 4pm - Monday 9am' \
  --ci-timeout='15min' \
  --git-timeout='20s' \
  --project-regexp='GROUP/SUBGROUP/.*' \
  --add-tested
```

the docker version is `Docker version 18.06.1-ce, build e68fc7a`

What went wrong?!

**Comment by JaimeLennox** [comment]
Can you run Marge in debug mode (`--debug`) and see what the response from the GitLab API is?

**Comment by snim2** [comment]
Since I raised this issue, I've managed to fix the problem. 

Our repos have this structure: `Group/Subgroup/{Project0, Project1, ...}` and the `marge-bot` user was an owner of `Group`, and therefore an owner of all the projects. I've removed the user from `Group` and added it as an owner of `Subgroup`, and now `marge-bot` works as expected. 

I'm not sure whether this is expected behaviour or just my misunderstanding. Please let me know if you still want me to run some `--debug` sessions.

**Comment by JaimeLennox** [comment]
Ah, ok. I think this is the same situation as #156 then - I'll close this in favour of that issue.
