### ISSUE TITLE
Marge bot merges a request and then comments that it couldn't merge the branch and it doesn't know why

### ISSUE THREAD

**Issue by mapatel7** [smarkets/marge-bot#174]
![marge-bot-failure](https://user-images.githubusercontent.com/47230375/55994895-dc5d4e00-5c67-11e9-84f8-3717ffe3b952.PNG)

For a merge request, marge-bot is able to merge it and after it does so, it comments as shown in the picture. Why is it commenting this after it is able to merge?

**Comment by snim2** [comment]
Is it possible that you have two instances of `marge-bot` running? This will tell you:

```sh
docker container list
```

**Comment by mapatel7** [comment]
Hello @snim2 ,

I have 3 instances of marge-bot running as services in a docker swarm. Is that the reason?

**Comment by snim2** [comment]
Hi there, if you have more than one marge-bot configured to merge MRs on the same set of repositories, inevitably you will end up with more than one of them trying to merge at the same time. It depends how you have everything set up, but if you want more than one marge-bot, I would suggest you configure them to process different repos.

**Comment by mapatel7** [comment]
That makes sense. I believe that could be the problem. If i encounter it again with them configured for different repos, i'll re-open this issue.

Thanks @snim2 

-Mithil

**Comment by snim2** [comment]
You're welcome!
