### ISSUE TITLE
GitLab pipeline API change: detached pipeline refs changed - Marge fails to detect pipeline

### ISSUE THREAD

**Issue by veeg** [smarkets/marge-bot#185]
Due to recent [GitLab API Change](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/25504), the refs slug received from [list pipelines](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines) returns a ref changed to format `refs/merge-requests/[MERGE_REQUEST_NUMBER]/head`, instead of `[BRANCH_NAME]`.

This is only applicable when the pipeline is ran on merge_requests, e.g., detached.

The following call needs to be augmented with a refs argument:
https://github.com/smarkets/marge-bot/blob/183be28fcac622c006dd81caa4fa62c2298d4834/marge/job.py#L138-L142

**Comment by veeg** [comment]
This API change has renderes Margebot useless for our deployment.

Does anyone have a suggestion on how this scenario should be handled, and I can have a stab at implementing it.

**Comment by dbinderAtCP** [comment]
We are stymied by this too. One thought could be to get all of the pipelines associated with the project_id, by adding an all_pipelines() method to Pipeline,  requiring the iterator in get_mr_ci_status() looking for the matching sha to deal with the longer list.
