### ISSUE TITLE
marge-bot stuck

### ISSUE THREAD

**Issue by snim2** [smarkets/marge-bot#201]
Recently we have found marge-bot (running in Docker) getting "stuck" -- i.e. pausing without reason, sometimes for several hours without reason. Marge isn't waiting on anything in particular, and because nothing is being printed in the log it's hard to know what caused the problem. Restarting marge-bot manually fixes the issue, so I doubt this was caused by exceeding a rate limit in the GitLab API.

I appreciate that this isn't a very useful issue to raise, since I can't reliably reproduce it. But if anyone has any advice on how to debug this one I'd really appreciated it.

**Comment by jcpetruzza** [comment]
Could you run it with debug logging to see if you can get a better insight of where it gets stuck?

**Comment by snim2** [comment]
Good question. That logging won't get written to the syslog on the host, will it? Is there an example config for Docker / marge-bot debugging?

**Comment by jcpetruzza** [comment]
IIRC, Marge logs to stdout and docker should pick that up. Do you get anything when running `docker logs <marge-container-name>`. Debug logging will just make it more verbose but should end in the same place

**Comment by jcpetruzza** [comment]
Also, I suspect you may be experiencing #188 ?

**Comment by snim2** [comment]
I think you are right. Ten minutes ago I had:

```
2019-06-10 16:45:07,698 DEBUG Starting new HTTPS connection (1): gitlab.com
```

and nothing since. So, I'll close this as a duplicate. Thanks for your advice!
