### ISSUE TITLE
Cannot seem to build on Ubuntu

### ISSUE THREAD

**Issue by dbinderAtCP** [smarkets/marge-bot#207]
I'm new to nix.
I would have assumed that using a base Ubuntu 18.04.2 instance, installing git, make, curl and nix and then cloning the marge-bot project and typing "make marge-bot" or "make dockerize" would just work.  It doesn't. I get the following errors. 

I must be doing something wrong.  I'd like to contribute to help fix issue 185 maybe 170 too, but not being able to build and deploy anything is hindering me.

[make_dockerize_full_log.txt](https://github.com/smarkets/marge-bot/files/3287159/make_dockerize_full_log.txt)
[make_margebot_error.txt](https://github.com/smarkets/marge-bot/files/3287160/make_margebot_error.txt)
[make_margebot_full_log.txt](https://github.com/smarkets/marge-bot/files/3287161/make_margebot_full_log.txt)

**Comment by jcpetruzza** [comment]
You may also need to install `docker` on Ubuntu, since the daemon is needed for ` make dockerize`, iirc

**Comment by dbinderAtCP** [comment]
I installed docker after posting, and although it gets rid of the docker not found, still does not address the other download issues.

**Comment by aschmolck** [comment]
Yes, your assumption is correct so this is a bug. I'll investigate properly beginning of next week, but in the meantime you could see if adding to requirements_override.nix unblocks you.

```  
"mccabe" = python.overrideDerivation super."mccabe" (old: {
     doCheck = false
  });
```

**Comment by JaimeLennox** [comment]
I believe #250 should have fixed this.
