### ISSUE TITLE
Support cloning via HTTPS

### ISSUE THREAD

**Issue by matthiasbalke** [smarkets/marge-bot#225]
Currently marge-bot always clones GIT repositories via SSH, which is fine in most cases, but our GitLab is setup to only provide HTTPS access. Currently we cannot change this.

It would be awesome to provide a way to choose between SSH and HTTPS cloning.

If someone points me in the right direction I'm willing to implement this as a PR.

**Comment by jcpetruzza** [comment]
You could start looking [here](https://github.com/smarkets/marge-bot/blob/07a7372845257209b92a4ed409c001703e7678f5/marge/bot.py#L33) and follow the calls. The `RepoManager` will clone a new repo when needed (see [here](https://github.com/smarkets/marge-bot/blob/07a7372845257209b92a4ed409c001703e7678f5/marge/store.py#L22)). You will need to get  the proper credentials to that point.

**Comment by matthiasbalke** [comment]
Just a quick not for others: Currently I don't work on this issue. I sadly do not have enough time. So if anybody is interested in implementing this., please go ahead.

**Comment by imflavio** [comment]
I've done this internally, but I had to disable the ssh option, or make it entirely optional. Not sure how you guys feel about that.
I believe it would be simpler to just remove ssh entirely and run https via token.
Also had to create a simple dockerfile to run the app, would you be interested in this as well?

**Comment by matthiasbalke** [comment]
@imflavio I would be interested in test driving your https implementation.

**Comment by imflavio** [comment]
Okay I'll create a PR tomorrow 👍

**Comment by imflavio** [comment]
@matthiasbalke Created it here: https://github.com/smarkets/marge-bot/pull/248

**Comment by matthiasbalke** [comment]
I finally found some time to implement this. I took @flaviouk idea and added a compatible argument parsing around it.
PR is #283
