### ISSUE TITLE
The first commit in the rebase has WIP when the merge title has WIP.

### ISSUE THREAD

**Issue by micheelengronne** [smarkets/marge-bot#237]
Keeping the `WIP:` in the first commit from rebasing when the title has `WIP:` makes the commits history dirtier as `WIP:` should not appear in any commit that goes to master.

Marge-bot should be able to remove `WIP:` from any commit when it rebases. `WIP:` is just a helper to keep the MR appart not a commit relevant content.

**Comment by qqshfox** [comment]
Don't think marge-bot should be aware of and change the title and content of a commit (except adding/updating trailers). Please reopen if I missed something obvious.
