### ISSUE TITLE
Add reference to original merge request in commit message

### ISSUE THREAD

**Issue by tomecki** [smarkets/marge-bot#25]
Marge could put a link to original merge request in the commit message, presumably for every commit in a MR.

**Comment by aschmolck** [comment]
Hi @tomecki, not exactly what you are asking for, but if you run marge with the `--add-tested` flag it does leave a link to the merge request in the final commit message (`Tested-by: Marge Bot <LINK>`).

So you know that all commits between two Tested-by: commits belong to the same merge request, namely the one listed in the second of these two commits. The reason I chose Tested-by and the final commit is that in addition to knowing where something came from, it's also very useful to know that this particular commit passed CI, and having an easy way to bisect skip commits that didn't.

**Comment by jcpetruzza** [comment]
I can imagine that having a `Part-of: <link to MR>` on every commit could be useful to easily find the context for a commit after a `git blame`. Is that the use case you had in mind?

It shouldn't be too hard to add, in case you want to give it a try: all the necessary bits, including how to add tag on every commit, are already in place.
