### ISSUE TITLE
 Add required approvals for gitlab ce

### ISSUE THREAD

**Issue by erikseifert** [smarkets/marge-bot#300]
Iw would be very nice to force all approvals for gitlab ce

```yml
require-approvals: true
```

**Comment by nejch** [comment]
This is essentially what I'm after in marge-bot. It's already implemented in https://github.com/smarkets/marge-bot/pull/254 in some way (not exactly how you describe it here) so you could use that fork.

**Comment by erikseifert** [comment]
Duplicate of #254
