### ISSUE TITLE
Improve error message when assigned to MR with unresolved threads

### ISSUE THREAD

**Issue by arvidj** [smarkets/marge-bot#317]
Currently, the message posted by marge on when attempting to merge an MR with outstanding threads is only:

> I couldn't merge this branch: Merge request was rejected by GitLab: 'Branch cannot be merged'

and the log message is:

>  | 2021-07-08 11:01:26,671 WARNING I couldn't merge this branch: Merge request was rejected by GitLab: 'Branch cannot be merged'

This could be improved by extending 

    def ensure_mergeable_mr(self, merge_request):

by retrieving all notes in the mr, and checking that all notes that are resolvable are also resolved.

**Comment by snim2** [comment]
I think it might be even simpler than that. In the [GitLab MR API](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr) there's a JSON key `blocking_discussions_resolved` which we can check.

**Comment by snim2** [comment]
OK, PR up and ready for review...
