### ISSUE TITLE
add --gitlab-url env equivalent

### ISSUE THREAD

**Issue by glensc** [smarkets/marge-bot#35]
seems from documentation that `--gitlab-url='http://your.gitlab.instance.com'` can be specified only via commandline.

please add `MARGE_GITLAB_URL` env var support, so i could use this easily via `docker-compose.yml`

probably should unify configuration that all commandline options are working via env vars as well (and vice versa). maybe [click](https://pypi.python.org/pypi/click) can help in this.

**Comment by jcpetruzza** [comment]
Makes sense to me

**Comment by jcpetruzza** [comment]
@glensc The version in #39 should do what you requested, in case you want to give it a try it before we merge it.

**Comment by glensc** [comment]
@jcpetruzza thanks. i probably will just wait it to be merged, too much hassle to figure out how the docker image is built and then build it myself :)
