### ISSUE TITLE
Make git pull timeout configurable

### ISSUE THREAD

**Issue by siebertm** [smarkets/marge-bot#54]
in [marge/git.py](https://github.com/smarkets/marge-bot/blob/master/marge/git.py#L12), you're hardcoding the git clone timeout to 120 seconds. While this may be a sensible default, it absolutely doesn't work for large repositories which take longer to clone.

I'd rather propose this to be configurable by either an environment variable (`MARGE_GIT_TIMEOUT`?) or a command option (or both?)

**Comment by glensc** [comment]
@siebertm never link to branch, use git tag or commit. `y` hotkey in github.

**Comment by aschmolck** [comment]
Fixed in 0.4.0
