### ISSUE TITLE
Barriers to marge-bot working with GitHub?

### ISSUE THREAD

**Issue by rmacklin** [smarkets/marge-bot#74]
Hi,

This project seems pretty interesting, and potentially quite useful. And I'm a big fan of GitLab. However, many organizations prefer GitHub to GitLab, which unfortunately means that, because marge-bot is built for GitLab, many organizations can't use this tool.

That makes me curious about what could be done to support either platform. I was hoping that those familiar with the project could outline what currently prevents marge-bot from working with GitHub, and perhaps we can then brainstorm some ideas for how we could get around some of these issues. (I'm imagining that most WebHook Events and APIs needed by marge-bot would exist on both platforms, so I'm hoping that maybe the idea of working on both platforms isn't too far out there...?)

Even if using marge-bot with GitHub came with some caveats that don't apply to GitLab use, having _something_ could certainly be better than nothing for organizations that are currently "stuck" on GitHub. But if there are some legitimate deal-breakers that completely prevent marge-bot from working in any capacity with GitHub, just listing those would also be a satisfactory answer to this issue. Either way, I think discussing this is worthwhile :)

Thanks!

_Edit:_ Of course, one big difference between the two is that GitLab has built-in CI. But I'm wondering how significant this difference is if we can assume that the GitHub repositories using this would have some CI service reporting status checks on each PR.

**Comment by rmacklin** [comment]
Of course, one big difference between the two is that GitLab has built-in CI. But I'm wondering how significant this difference is if we can assume that the GitHub repositories using this would have some CI service reporting status checks when a PR is opened (or on every commit pushed)

**Comment by aschmolck** [comment]
The only barrier I'm *aware* of is that no one has put in the work to 

a) refactor marge to allow for multiple backends
b) add a github backend 

I haven't spent enough time to be certain, but I believe github has the requisite API facilities, e.g. you've been able to query (for example) travis CI status via the API for a long time:

https://github.com/blog/1227-commit-status-api

you can also issue merge requests (plain merge, squash and rebase) via the API:

https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

My not very substantiated guess is that if this is something you deeply care about you could probably hack up a prototype fork of marge-bot that replaces all gitlab API calls with github equivalents in less than a weekend.

This would already be useful in itself, and from there one could figure out what the best way to structure the code would be (e.g. a single project that can talk to either gitlab or github or two different projects that both share some common core functionality which could live in a third repo, ... etc). This likely will depend on both technical and social factors (e.g. for github support to be included in the main project, continued maintenance would need to be ensured somehow).

I think it would be pretty cool to support github, so if there's a working prototype, I'd be interested in moving it forward.
