### ISSUE TITLE
Is it possible to provide alternative of required approvals for Gitlab CE editions

### ISSUE THREAD

**Issue by amimas** [smarkets/marge-bot#83]
I believe approval requirement for a merge request is available for Gitlab EE only. In CE edition, this option is not available. So, is there any other way of protecting unwanted merges by merge-bot?

**Comment by aschmolck** [comment]
It might be possible to hack something up (e.g. using thumb sup or down and specifying list of approvers out of band), but I'm not really in favor of doing that since I don't want to add EE features through the backdoor (and screw with gitlab's business model).

**Comment by amimas** [comment]
That's a very good point and I agree with you. Closing this issue.
