### ISSUE TITLE
Fix/investigate corner case of no-op merge request

### ISSUE THREAD

**Issue by aschmolck** [smarkets/marge-bot#9]
This can happen when the commit messages of source and target differ, but content is identical; there is an example in our internal marge-test-repo. The weird thing we observed in that case is that rebasing into the target branch did not update the branch reference (i.e. unexpected git behavior which we should try to understand; possibly a bug more likely an UX issue or us missing something).

**Comment by JaimeLennox** [comment]
Probably fixed in https://github.com/smarkets/marge-bot/commit/9986daf294673ad58a06c7ca19125bc20c144c96?

**Comment by aschmolck** [comment]
Yup, let's close this – thanks for fixing! :)
