### ISSUE TITLE
Configurable ci backend?

### ISSUE THREAD

**Issue by piclemx** [smarkets/marge-bot#99]
Would that be possible to have a different ci then gitlab-ci

**Comment by jcpetruzza** [comment]
I don't think marge relies on gitlab-ci being used. It will query gitlab's REST Api and ask about the status of the build for that PR. So if you are using, say, the jenkins plugin, this will be transparent.

Is this not working for you in some way?

**Comment by piclemx** [comment]
I have not try it yet, but i think our configuration with jenkins is with webhook 🤔 ... so i don't think gitlab have the status of the build. Do you know if the bot can acknowledge a open merge request to a slack channel example (no wip acknowledge) or a merge request being merge?

**Comment by JaimeLennox** [comment]
Jenkins has a plugin for GitLab: https://plugins.jenkins.io/gitlab-plugin

If you use this, Gitlab (and Marge) will receive the status of the build.

**Comment by JaimeLennox** [comment]
Closing, as this is already possible (https://docs.gitlab.com/ee/integration/jenkins.html)
